version: '3.7'
name: lu_estilo

services:
  api:
    build: .
    command: "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    volumes:
      - ./:/app
    ports:
      - 8080:8000
    environment:
      - PORT=8000
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - 3587:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}